### PR TITLE
Publishing the full version to live

### PR DESCRIPTION
**Pull request by askalburgi**

### CODE REVIEW

**Comment by gantonious** [comment]
The site does not seem to render well on mobile right now. All these screenshots are based off of the iPhone 6. Here are the main issues:

- The HackED Beta logo is right now split on three lines
- You cant see all the overlapping buttons at the same time and they are also not centered. I really think these buttons should be visible together even on mobile and the content they control underneath should be visible as well so the user understands what clicking the button does
- The FAQ is cut off on the right on mobile
- The margins in the contact are are way too small
 
image

**Comment by gantonious** [comment]
The FAQ sections glitches out sometimes when opening up a new FAQ:

**Comment by gantonious** [comment]
Some of the FAQs are not done or have stale information:

- "Who organizes HackEDbeta?" has the content from "Do I need to know programming?"
- "Are there any fees?" still has the $15 entrance fee

**Comment by gantonious** [comment]
The text color on the FAQ section is kind of hard on the eyes for the red and blue background. I think we should change the text color depending on the background to get the best contrast.

**Comment by gantonious** [comment]
The sponsors section is still empty.

**Comment by askalburgi** [comment]
I'm *SOOOOO* confused. 
image
Like the sponsors are here! 
And if you pull down betabeta, it's there!

**Comment by gantonious** [comment]
The images aren't in root ;) I fixed them with my last commit.

**Comment by gantonious** [comment]
The gfycat logo is not vertically aligned with the rest though:

image

**Comment by gantonious** [comment]
Rip the flexbox stuff I used in the sponsorship section doesn't work on safari.

**Pull request merged**
